"""
Q10. Write a custom iterator class that returns numbers from 1 to N.
"""

MAX_NUMBER = 5


class NumberIterator:
    """
    Custom iterator that returns numbers from 1 to N.
    """

    def __init__(self, limit: int) -> None:
        self.limit = limit
        self.current_number = 1

    def __iter__(self):
        return self

    def __next__(self) -> int:
        if self.current_number <= self.limit:
            number = self.current_number
            self.current_number += 1
            return number

        raise StopIteration


def print_numbers(limit: int) -> None:
    """
    Prints numbers generated by the custom iterator.
    """
    for number in NumberIterator(limit):
        print(number)


if __name__ == "__main__":
    print_numbers(MAX_NUMBER)