"""
Q12. Write a generator to produce Fibonacci numbers.
"""

NUMBER_OF_TERMS = 10


def generate_fibonacci(limit: int):
    """
    Generates Fibonacci numbers.
    """
    first_number = 0
    second_number = 1

    for _ in range(limit):
        yield first_number
        first_number, second_number = (
            second_number,
            first_number + second_number
        )


def print_fibonacci_numbers(limit: int) -> None:
    """
    Prints Fibonacci numbers generated by the generator.
    """
    for number in generate_fibonacci(limit):
        print(number)


if __name__ == "__main__":
    print_fibonacci_numbers(NUMBER_OF_TERMS)