"""
Q16. Show an example of a built-in generator (like range)
and iterate over it.
"""

START_NUMBER = 1
END_NUMBER = 5


def print_numbers() -> None:
    """
    Iterates over numbers generated by range().
    """
    for number in range(START_NUMBER, END_NUMBER + 1):
        print(number)


if __name__ == "__main__":
    print_numbers()