package com.nucleusteq.interviewtracker.entity;

import com.nucleusteq.interviewtracker.enums.InterviewStage;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a candidate who has applied for a job.
 * Stores complete profile information along with their
 * current stage in the interview process.
 * A candidate can only apply for one job at a time.
 */
@Entity
@Table(name = "candidate")
public class Candidate {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full name of the candidate. */
    @Column(name = "full_name", nullable = false)
    private String fullName;

    /** Email address — must be unique, no duplicate applications allowed. */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /** Country code for mobile number e.g. +91 for India. */
    @Column(name = "mobile_code", nullable = false)
    private String mobileCode;

    /** Mobile number — must be unique, no duplicate applications allowed. */
    @Column(name = "mobile_number", nullable = false, unique = true)
    private String mobileNumber;

    /** Date of birth — optional as per the spec. */
    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;

    /** File path where the candidate's resume PDF is stored on the server. */
    @Column(name = "resume_path")
    private String resumePath;

    /** Name of the company where the candidate currently works. */
    @Column(name = "current_organization", nullable = false)
    private String currentOrganization;

    /** Total years of work experience across all roles. */
    @Column(name = "total_experience", nullable = false)
    private Double totalExperience;

    /** Years of experience relevant to the job applied for. */
    @Column(name = "relevant_experience", nullable = false)
    private Double relevantExperience;

    /** Current salary in LPA. */
    @Column(name = "current_ctc", nullable = false)
    private Double currentCtc;

    /** Expected salary in LPA. */
    @Column(name = "expected_ctc", nullable = false)
    private Double expectedCtc;

    /** Number of days required before the candidate can join. */
    @Column(name = "notice_period", nullable = false)
    private Integer noticePeriod;

    /** City or location where the candidate prefers to work. */
    @Column(name = "preferred_location", nullable = false)
    private String preferredLocation;

    /** How the candidate found this job e.g. LinkedIn, Naukri, Referral. */
    @Column(name = "source", nullable = false)
    private String source;

    /** Current stage of the candidate in the interview process.
     *  Starts at PROFILING and is moved forward manually by HR. */
    @Enumerated(EnumType.STRING)
    @Column(name = "current_stage", nullable = false)
    private InterviewStage currentStage = InterviewStage.PROFILING;

    /** Timestamp when this candidate profile was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** The job description this candidate has applied for. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "jd_id", nullable = false)
    private JobDescription jobDescription;

    /** The user account linked to this candidate for login. */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Default constructor required by JPA.
     */
    public Candidate() {
    }

    /**
     * Creates a new candidate profile with all required fields.
     * Current stage is set to PROFILING and createdAt is set automatically.
     *
     * @param fullName             full name of the candidate
     * @param email                unique email address
     * @param mobileCode           country code e.g. +91
     * @param mobileNumber         unique mobile number
     * @param currentOrganization  current employer name
     * @param totalExperience      total years of experience
     * @param relevantExperience   relevant years of experience
     * @param currentCtc           current salary in LPA
     * @param expectedCtc          expected salary in LPA
     * @param noticePeriod         notice period in days
     * @param preferredLocation    preferred work location
     * @param source               how candidate found this job
     * @param jobDescription       the JD this candidate applied for
     * @param user                 linked user account for login
     */
    public Candidate(String fullName, String email, String mobileCode,
            String mobileNumber, String currentOrganization,
            Double totalExperience, Double relevantExperience,
            Double currentCtc, Double expectedCtc,
            Integer noticePeriod, String preferredLocation,
            String source, JobDescription jobDescription, User user) {
        this.fullName = fullName;
        this.email = email;
        this.mobileCode = mobileCode;
        this.mobileNumber = mobileNumber;
        this.currentOrganization = currentOrganization;
        this.totalExperience = totalExperience;
        this.relevantExperience = relevantExperience;
        this.currentCtc = currentCtc;
        this.expectedCtc = expectedCtc;
        this.noticePeriod = noticePeriod;
        this.preferredLocation = preferredLocation;
        this.source = source;
        this.jobDescription = jobDescription;
        this.user = user;
        this.currentStage = InterviewStage.PROFILING;
        this.createdAt = LocalDateTime.now();
    }

    /** @return the candidate's database id. */
    public Long getId() {
        return id;
    }

    /** @param id the id to set. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the full name of the candidate. */
    public String getFullName() {
        return fullName;
    }

    /** @param fullName the full name to set. */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /** @return the email address of the candidate. */
    public String getEmail() {
        return email;
    }

    /** @param email the email to set. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** @return the mobile country code. */
    public String getMobileCode() {
        return mobileCode;
    }

    /** @param mobileCode the mobile code to set. */
    public void setMobileCode(String mobileCode) {
        this.mobileCode = mobileCode;
    }

    /** @return the mobile number of the candidate. */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /** @param mobileNumber the mobile number to set. */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /** @return the date of birth — may be null as it is optional. */
    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    /** @param dateOfBirth the date of birth to set. */
    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /** @return the file path of the uploaded resume PDF. */
    public String getResumePath() {
        return resumePath;
    }

    /** @param resumePath the resume file path to set. */
    public void setResumePath(String resumePath) {
        this.resumePath = resumePath;
    }

    /** @return the current organization of the candidate. */
    public String getCurrentOrganization() {
        return currentOrganization;
    }

    /** @param currentOrganization the organization to set. */
    public void setCurrentOrganization(String currentOrganization) {
        this.currentOrganization = currentOrganization;
    }

    /** @return the total years of experience. */
    public Double getTotalExperience() {
        return totalExperience;
    }

    /** @param totalExperience the total experience to set. */
    public void setTotalExperience(Double totalExperience) {
        this.totalExperience = totalExperience;
    }

    /** @return the relevant years of experience. */
    public Double getRelevantExperience() {
        return relevantExperience;
    }

    /** @param relevantExperience the relevant experience to set. */
    public void setRelevantExperience(Double relevantExperience) {
        this.relevantExperience = relevantExperience;
    }

    /** @return the current CTC in LPA. */
    public Double getCurrentCtc() {
        return currentCtc;
    }

    /** @param currentCtc the current CTC to set. */
    public void setCurrentCtc(Double currentCtc) {
        this.currentCtc = currentCtc;
    }

    /** @return the expected CTC in LPA. */
    public Double getExpectedCtc() {
        return expectedCtc;
    }

    /** @param expectedCtc the expected CTC to set. */
    public void setExpectedCtc(Double expectedCtc) {
        this.expectedCtc = expectedCtc;
    }

    /** @return the notice period in days. */
    public Integer getNoticePeriod() {
        return noticePeriod;
    }

    /** @param noticePeriod the notice period to set. */
    public void setNoticePeriod(Integer noticePeriod) {
        this.noticePeriod = noticePeriod;
    }

    /** @return the preferred work location. */
    public String getPreferredLocation() {
        return preferredLocation;
    }

    /** @param preferredLocation the preferred location to set. */
    public void setPreferredLocation(String preferredLocation) {
        this.preferredLocation = preferredLocation;
    }

    /** @return the source through which candidate found this job. */
    public String getSource() {
        return source;
    }

    /** @param source the source to set. */
    public void setSource(String source) {
        this.source = source;
    }

    /** @return the current interview stage of the candidate. */
    public InterviewStage getCurrentStage() {
        return currentStage;
    }

    /** @param currentStage the interview stage to set. */
    public void setCurrentStage(InterviewStage currentStage) {
        this.currentStage = currentStage;
    }

    /** @return the timestamp when this profile was created. */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp to set. */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /** @return the job description this candidate applied for. */
    public JobDescription getJobDescription() {
        return jobDescription;
    }

    /** @param jobDescription the job description to set. */
    public void setJobDescription(JobDescription jobDescription) {
        this.jobDescription = jobDescription;
    }

    /** @return the linked user account for login. */
    public User getUser() {
        return user;
    }

    /** @param user the user account to set. */
    public void setUser(User user) {
        this.user = user;
    }
}