package com.nucleusteq.interviewtracker.entity;

import com.nucleusteq.interviewtracker.enums.FeedbackStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * Represents the feedback submitted by a panel member
 * after conducting an L1 or L2 interview.
 * All fields are mandatory — panel cannot submit without filling everything.
 * Only HR can view this feedback — candidates cannot see it.
 */
@Entity
@Table(name = "feedback")
public class Feedback {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** General comments about the candidate's overall performance. */
    @Column(name = "comments", nullable = false, columnDefinition = "TEXT")
    private String comments;

    /** Strong points observed in the candidate during the interview. */
    @Column(name = "strengths", nullable = false, columnDefinition = "TEXT")
    private String strengths;

    /** Areas where the candidate needs improvement. */
    @Column(name = "weaknesses", nullable = false, columnDefinition = "TEXT")
    private String weaknesses;

    /** Topics discussed during the interview e.g. DSA, Spring Boot, SQL. */
    @Column(name = "areas_covered", nullable = false, columnDefinition = "TEXT")
    private String areasCovered;

    /** Rating given by the panel member on a scale of 1 to 5. */
    @Column(name = "rating", nullable = false)
    private Integer rating;

    /** Panel member's recommendation — SELECTED or REJECTED.
     *  This is not the final decision, HR makes the final call. */
    @Enumerated(EnumType.STRING)
    @Column(name = "feedback_status", nullable = false)
    private FeedbackStatus feedbackStatus;

    /** Timestamp when this feedback was submitted. */
    @Column(name = "submitted_at", nullable = false)
    private LocalDateTime submittedAt;

    /** The interview this feedback belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "interview_id", nullable = false)
    private Interview interview;

    /** The panel member who submitted this feedback. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "panel_member_id", nullable = false)
    private PanelMember panelMember;

    /**
     * Default constructor required by JPA.
     */
    public Feedback() {
    }

    /**
     * Creates a new feedback record with all mandatory fields.
     * submittedAt is set automatically to the current time.
     *
     * @param comments        general performance comments
     * @param strengths       candidate's strong points
     * @param weaknesses      areas needing improvement
     * @param areasCovered    topics discussed in the interview
     * @param rating          score from 1 to 5
     * @param feedbackStatus  panel's recommendation — SELECTED or REJECTED
     * @param interview       the interview this feedback belongs to
     * @param panelMember     the panel member submitting this feedback
     */
    public Feedback(String comments, String strengths,
            String weaknesses, String areasCovered,
            Integer rating, FeedbackStatus feedbackStatus,
            Interview interview, PanelMember panelMember) {
        this.comments = comments;
        this.strengths = strengths;
        this.weaknesses = weaknesses;
        this.areasCovered = areasCovered;
        this.rating = rating;
        this.feedbackStatus = feedbackStatus;
        this.interview = interview;
        this.panelMember = panelMember;
        this.submittedAt = LocalDateTime.now();
    }

    /** @return the feedback id. */
    public Long getId() {
        return id;
    }

    /** @param id the id to set. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return general comments about the candidate. */
    public String getComments() {
        return comments;
    }

    /** @param comments the comments to set. */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /** @return the strengths observed in the candidate. */
    public String getStrengths() {
        return strengths;
    }

    /** @param strengths the strengths to set. */
    public void setStrengths(String strengths) {
        this.strengths = strengths;
    }

    /** @return the weaknesses observed in the candidate. */
    public String getWeaknesses() {
        return weaknesses;
    }

    /** @param weaknesses the weaknesses to set. */
    public void setWeaknesses(String weaknesses) {
        this.weaknesses = weaknesses;
    }

    /** @return the topics covered during the interview. */
    public String getAreasCovered() {
        return areasCovered;
    }

    /** @param areasCovered the areas covered to set. */
    public void setAreasCovered(String areasCovered) {
        this.areasCovered = areasCovered;
    }

    /** @return the rating given by the panel member. */
    public Integer getRating() {
        return rating;
    }

    /** @param rating the rating to set — must be between 1 and 5. */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /** @return the panel member's recommendation. */
    public FeedbackStatus getFeedbackStatus() {
        return feedbackStatus;
    }

    /** @param feedbackStatus the feedback status to set. */
    public void setFeedbackStatus(FeedbackStatus feedbackStatus) {
        this.feedbackStatus = feedbackStatus;
    }

    /** @return the timestamp when feedback was submitted. */
    public LocalDateTime getSubmittedAt() {
        return submittedAt;
    }

    /** @param submittedAt the submission timestamp to set. */
    public void setSubmittedAt(LocalDateTime submittedAt) {
        this.submittedAt = submittedAt;
    }

    /** @return the interview this feedback belongs to. */
    public Interview getInterview() {
        return interview;
    }

    /** @param interview the interview to set. */
    public void setInterview(Interview interview) {
        this.interview = interview;
    }

    /** @return the panel member who submitted this feedback. */
    public PanelMember getPanelMember() {
        return panelMember;
    }

    /** @param panelMember the panel member to set. */
    public void setPanelMember(PanelMember panelMember) {
        this.panelMember = panelMember;
    }
}