package com.nucleusteq.interviewtracker.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * Represents the assignment of a panel member to an interview.
 * Acts as a mapping table between Interview and PanelMember.
 * One interview can have minimum 1 and maximum 2 panel members assigned.
 */
@Entity
@Table(name = "interview_panel")
public class InterviewPanel {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The interview this panel assignment belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "interview_id", nullable = false)
    private Interview interview;

    /** The panel member assigned to conduct this interview. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "panel_member_id", nullable = false)
    private PanelMember panelMember;

    /** Timestamp when HR made this assignment. */
    @Column(name = "assigned_at", nullable = false)
    private LocalDateTime assignedAt;

    /**
     * Default constructor required by JPA.
     */
    public InterviewPanel() {
    }

    /**
     * Creates a new panel assignment linking a panel member to an interview.
     * assignedAt is set automatically to the current time.
     *
     * @param interview    the interview to assign the panel member to
     * @param panelMember  the panel member being assigned
     */
    public InterviewPanel(Interview interview, PanelMember panelMember) {
        this.interview = interview;
        this.panelMember = panelMember;
        this.assignedAt = LocalDateTime.now();
    }

    /** @return the assignment id. */
    public Long getId() {
        return id;
    }

    /** @param id the id to set. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the interview this assignment belongs to. */
    public Interview getInterview() {
        return interview;
    }

    /** @param interview the interview to set. */
    public void setInterview(Interview interview) {
        this.interview = interview;
    }

    /** @return the panel member assigned to this interview. */
    public PanelMember getPanelMember() {
        return panelMember;
    }

    /** @param panelMember the panel member to set. */
    public void setPanelMember(PanelMember panelMember) {
        this.panelMember = panelMember;
    }

    /** @return the timestamp when this assignment was created. */
    public LocalDateTime getAssignedAt() {
        return assignedAt;
    }

    /** @param assignedAt the assignment timestamp to set. */
    public void setAssignedAt(LocalDateTime assignedAt) {
        this.assignedAt = assignedAt;
    }
}