package com.nucleusteq.interviewtracker.entity;

import com.nucleusteq.interviewtracker.enums.InterviewStage;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Table;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents an interview scheduled for a candidate.
 * Handles L1 Technical, L2 Technical and HR Round interviews.
 * HR schedules the interview by selecting panel members,
 * setting date, time and providing focus areas.
 */
@Entity
@Table(name = "interview")
public class Interview {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Stage this interview belongs to — L1_TECHNICAL, L2_TECHNICAL or HR_ROUND. */
    @Enumerated(EnumType.STRING)
    @Column(name = "interview_stage", nullable = false)
    private InterviewStage interviewStage;

    /** Date on which the interview is scheduled. */
    @Column(name = "interview_date", nullable = false)
    private LocalDate interviewDate;

    /** Time at which the interview is scheduled. */
    @Column(name = "interview_time", nullable = false)
    private LocalTime interviewTime;

    /** Topics HR wants the panel to focus on during the interview. */
    @Column(name = "focus_areas", columnDefinition = "TEXT")
    private String focusAreas;

    /** HR's final comments — mandatory only during the HR Round. */
    @Column(name = "hr_comments", columnDefinition = "TEXT")
    private String hrComments;

    /** Whether this interview has been completed. */
    @Column(name = "is_completed", nullable = false)
    private boolean isCompleted = false;

    /** Timestamp when this interview was scheduled by HR. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** The candidate this interview is scheduled for. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "candidate_id", nullable = false)
    private Candidate candidate;

    /** List of panel members assigned to this interview — min 1, max 2. */
    @OneToMany(mappedBy = "interview", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private List<InterviewPanel> interviewPanels = new ArrayList<>();

    /** List of feedback submitted by panel members for this interview. */
    @OneToMany(mappedBy = "interview", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private List<Feedback> feedbacks = new ArrayList<>();

    /**
     * Default constructor required by JPA.
     */
    public Interview() {
    }

    /**
     * Creates a new interview with all required fields.
     * isCompleted is set to false and createdAt is set automatically.
     *
     * @param interviewStage  the stage — L1_TECHNICAL, L2_TECHNICAL or HR_ROUND
     * @param interviewDate   date of the interview
     * @param interviewTime   time of the interview
     * @param focusAreas      topics HR wants panel to focus on
     * @param candidate       the candidate being interviewed
     */
    public Interview(InterviewStage interviewStage, LocalDate interviewDate,
            LocalTime interviewTime, String focusAreas,
            Candidate candidate) {
        this.interviewStage = interviewStage;
        this.interviewDate = interviewDate;
        this.interviewTime = interviewTime;
        this.focusAreas = focusAreas;
        this.candidate = candidate;
        this.isCompleted = false;
        this.createdAt = LocalDateTime.now();
    }

    /** @return the interview id. */
    public Long getId() {
        return id;
    }

    /** @param id the id to set. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the stage of this interview. */
    public InterviewStage getInterviewStage() {
        return interviewStage;
    }

    /** @param interviewStage the interview stage to set. */
    public void setInterviewStage(InterviewStage interviewStage) {
        this.interviewStage = interviewStage;
    }

    /** @return the date of the interview. */
    public LocalDate getInterviewDate() {
        return interviewDate;
    }

    /** @param interviewDate the interview date to set. */
    public void setInterviewDate(LocalDate interviewDate) {
        this.interviewDate = interviewDate;
    }

    /** @return the time of the interview. */
    public LocalTime getInterviewTime() {
        return interviewTime;
    }

    /** @param interviewTime the interview time to set. */
    public void setInterviewTime(LocalTime interviewTime) {
        this.interviewTime = interviewTime;
    }

    /** @return the focus areas for this interview. */
    public String getFocusAreas() {
        return focusAreas;
    }

    /** @param focusAreas the focus areas to set. */
    public void setFocusAreas(String focusAreas) {
        this.focusAreas = focusAreas;
    }

    /** @return the HR round final comments. */
    public String getHrComments() {
        return hrComments;
    }

    /** @param hrComments the HR comments to set. */
    public void setHrComments(String hrComments) {
        this.hrComments = hrComments;
    }

    /** @return true if the interview has been completed. */
    public boolean isCompleted() {
        return isCompleted;
    }

    /** @param completed true if interview is completed, false otherwise. */
    public void setCompleted(boolean completed) {
        isCompleted = completed;
    }

    /** @return the timestamp when this interview was created. */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp to set. */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /** @return the candidate this interview is for. */
    public Candidate getCandidate() {
        return candidate;
    }

    /** @param candidate the candidate to set. */
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    /** @return the list of panel assignments for this interview. */
    public List<InterviewPanel> getInterviewPanels() {
        return interviewPanels;
    }

    /** @param interviewPanels the panel assignments to set. */
    public void setInterviewPanels(List<InterviewPanel> interviewPanels) {
        this.interviewPanels = interviewPanels;
    }

    /** @return the list of feedback submitted for this interview. */
    public List<Feedback> getFeedbacks() {
        return feedbacks;
    }

    /** @param feedbacks the feedback list to set. */
    public void setFeedbacks(List<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }
}