package com.nucleusteq.interviewtracker.entity;

import com.nucleusteq.interviewtracker.enums.JobType;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a Job Description posted by HR.
 * Visible to all users on the homepage.
 * Candidates apply for a specific JD.
 * Each JD can have multiple skills associated with it.
 */
@Entity
@Table(name = "job_description")
public class JobDescription {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Title of the job posting e.g. Backend Developer. */
    @Column(name = "job_title", nullable = false)
    private String jobTitle;

    /** Detailed description of the role and responsibilities. */
    @Column(name = "job_description", nullable = false, columnDefinition = "TEXT")
    private String jobDescription;

    /** Minimum years of experience required for this role. */
    @Column(name = "min_experience", nullable = false)
    private Integer minExperience;

    /** Maximum years of experience required for this role. */
    @Column(name = "max_experience", nullable = false)
    private Integer maxExperience;

    /** Minimum salary offered for this role in LPA. */
    @Column(name = "min_salary", nullable = false)
    private Double minSalary;

    /** Maximum salary offered for this role in LPA. */
    @Column(name = "max_salary", nullable = false)
    private Double maxSalary;

    /** Location where the job is based e.g. Bangalore, Hyderabad. */
    @Column(name = "location", nullable = false)
    private String location;

    /** Type of employment — FULL_TIME, CONTRACT or REMOTE. */
    @Enumerated(EnumType.STRING)
    @Column(name = "job_type", nullable = false)
    private JobType jobType;

    /** Whether this job posting is currently open for applications. */
    @Column(name = "is_active", nullable = false)
    private boolean isActive = true;

    /** Timestamp when this job description was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** List of skills required for this job.
     *  Deleting a JD will also delete all its associated skills. */
    @OneToMany(mappedBy = "jobDescription", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private List<Skill> skills = new ArrayList<>();

    /**
     * Default constructor required by JPA.
     */
    public JobDescription() {
    }

    /**
     * Creates a new job description with all required fields.
     */
    public JobDescription(String jobTitle, String jobDescription,
            Integer minExperience, Integer maxExperience,
            Double minSalary, Double maxSalary,
            String location, JobType jobType) {
        this.jobTitle = jobTitle;
        this.jobDescription = jobDescription;
        this.minExperience = minExperience;
        this.maxExperience = maxExperience;
        this.minSalary = minSalary;
        this.maxSalary = maxSalary;
        this.location = location;
        this.jobType = jobType;
        this.isActive = true;
        this.createdAt = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJobTitle() {
        return jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getJobDescription() {
        return jobDescription;
    }

    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription;
    }

    public Integer getMinExperience() {
        return minExperience;
    }

    public void setMinExperience(Integer minExperience) {
        this.minExperience = minExperience;
    }

    public Integer getMaxExperience() {
        return maxExperience;
    }

    public void setMaxExperience(Integer maxExperience) {
        this.maxExperience = maxExperience;
    }

    public Double getMinSalary() {
        return minSalary;
    }

    public void setMinSalary(Double minSalary) {
        this.minSalary = minSalary;
    }

    public Double getMaxSalary() {
        return maxSalary;
    }

    public void setMaxSalary(Double maxSalary) {
        this.maxSalary = maxSalary;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public JobType getJobType() {
        return jobType;
    }

    public void setJobType(JobType jobType) {
        this.jobType = jobType;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public List<Skill> getSkills() {
        return skills;
    }

    public void setSkills(List<Skill> skills) {
        this.skills = skills;
    }
}