package com.nucleusteq.interviewtracker.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * Represents a panel member in the system.
 * Panel members are interviewers who conduct L1 and L2 interviews.
 * They are created by HR and cannot self-register.
 * Account is activated by HR which triggers an email with a
 * secure link for the panel member to set their password.
 */
@Entity
@Table(name = "panel_member")
public class PanelMember {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Mobile number — must be unique across all panel members. */
    @Column(name = "mobile_number", nullable = false, unique = true)
    private String mobileNumber;

    /** Company or organization the panel member works for. */
    @Column(name = "organization", nullable = false)
    private String organization;

    /** Job title of the panel member e.g. Senior Developer, Tech Lead. */
    @Column(name = "designation", nullable = false)
    private String designation;

    /** Timestamp when HR created this panel member account. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** Linked user account for login — null until panel member sets password. */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = true)
    private User user;

    /**
     * Default constructor required by JPA.
     */
    public PanelMember() {
    }

    /**
     * Creates a new panel member with all required fields.
     * createdAt is set automatically.
     */
    public PanelMember(String mobileNumber, String organization,
            String designation) {
        this.mobileNumber = mobileNumber;
        this.organization = organization;
        this.designation = designation;
        this.createdAt = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFullName() {
        // Return from User entity - single source of truth
        return user != null ? user.getFullName() : null;
    }

    public String getEmail() {
        // Return from User entity - single source of truth
        return user != null ? user.getEmail() : null;
    }

    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getOrganization() {
        return organization;
    }

    public void setOrganization(String organization) {
        this.organization = organization;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    public boolean isActive() {
        // Return from User entity - single source of truth
        return user != null && user.isActive();
    }

    public void setActive(boolean active) {
        // Delegate to User entity
        if (this.user != null) {
            this.user.setActive(active);
        }
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}