package com.nucleusteq.interviewtracker.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * Represents a panel member in the system.
 * Panel members are interviewers who conduct L1 and L2 interviews.
 * They are created by HR and cannot self-register.
 * Account is activated by HR which triggers an email with a
 * secure link for the panel member to set their password.
 */
@Entity
@Table(name = "panel_member")
public class PanelMember {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full name of the panel member. */
    @Column(name = "full_name", nullable = false)
    private String fullName;

    /** Email address — used for login and sending the activation link. */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /** Mobile number — must be unique across all panel members. */
    @Column(name = "mobile_number", nullable = false, unique = true)
    private String mobileNumber;

    /** Company or organization the panel member works for. */
    @Column(name = "organization", nullable = false)
    private String organization;

    /** Job title of the panel member e.g. Senior Developer, Tech Lead. */
    @Column(name = "designation", nullable = false)
    private String designation;

    /** Whether HR has activated this panel member's account.
     *  Starts as false — becomes true after panel member sets their password. */
    @Column(name = "is_active", nullable = false)
    private boolean isActive = false;

    /** Timestamp when HR created this panel member account. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** Linked user account for login — null until panel member sets password. */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = true)
    private User user;

    /**
     * Default constructor required by JPA.
     */
    public PanelMember() {
    }

    /**
     * Creates a new panel member with all required fields.
     * isActive is set to false and createdAt is set automatically.
     * User account is null initially — linked after activation.
     *
     * @param fullName      full name of the panel member
     * @param email         unique email address
     * @param mobileNumber  unique mobile number
     * @param organization  company the panel member works for
     * @param designation   job title of the panel member
     */
    public PanelMember(String fullName, String email,
            String mobileNumber, String organization,
            String designation) {
        this.fullName = fullName;
        this.email = email;
        this.mobileNumber = mobileNumber;
        this.organization = organization;
        this.designation = designation;
        this.isActive = false;
        this.createdAt = LocalDateTime.now();
    }

    /** @return the panel member id. */
    public Long getId() {
        return id;
    }

    /** @param id the id to set. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the full name of the panel member. */
    public String getFullName() {
        return fullName;
    }

    /** @param fullName the full name to set. */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /** @return the email address of the panel member. */
    public String getEmail() {
        return email;
    }

    /** @param email the email to set. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** @return the mobile number of the panel member. */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /** @param mobileNumber the mobile number to set. */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /** @return the organization the panel member works for. */
    public String getOrganization() {
        return organization;
    }

    /** @param organization the organization to set. */
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    /** @return the designation of the panel member. */
    public String getDesignation() {
        return designation;
    }

    /** @param designation the designation to set. */
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    /** @return true if the panel member account is active. */
    public boolean isActive() {
        return isActive;
    }

    /** @param active true to activate the account, false otherwise. */
    public void setActive(boolean active) {
        isActive = active;
    }

    /** @return the timestamp when this account was created. */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp to set. */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /** @return the linked user account — null until password is set. */
    public User getUser() {
        return user;
    }

    /** @param user the user account to set. */
    public void setUser(User user) {
        this.user = user;
    }
}