package com.nucleusteq.interviewtracker.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a single skill required for a Job Description.
 * Stored in a separate table to support multi-select skills per JD.
 * One JD can have multiple skills e.g. Java, Spring Boot, MySQL.
 */
@Entity
@Table(name = "skills")
public class Skill {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Name of the skill e.g. Java, Spring Boot, MySQL, React. */
    @Column(name = "skill_name", nullable = false)
    private String skillName;

    /** The job description this skill belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "jd_id", nullable = false)
    private JobDescription jobDescription;

    /**
     * Default constructor required by JPA.
     */
    public Skill() {
    }

    /**
     * Creates a new skill linked to a job description.
     */
    public Skill(String skillName, JobDescription jobDescription) {
        this.skillName = skillName;
        this.jobDescription = jobDescription;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSkillName() {
        return skillName;
    }

    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }

    public JobDescription getJobDescription() {
        return jobDescription;
    }

    public void setJobDescription(JobDescription jobDescription) {
        this.jobDescription = jobDescription;
    }
}