package com.nucleusteq.interviewtracker.entity;

import com.nucleusteq.interviewtracker.enums.UserRole;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * Represents a user in the system.
 * Base entity for authentication and authorization.
 * All three roles — HR, PANEL and CANDIDATE — have a User account.
 * Panel accounts start inactive until they set their password via email link.
 */
@Entity
@Table(name = "users")
public class User {

    /** Primary key — auto generated by database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full name of the user. */
    @Column(name = "full_name", nullable = false)
    private String fullName;

    /** Email address used as the login username — must be unique. */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /** Encrypted password — never stored as plain text. */
    @Column(name = "password", nullable = false)
    private String password;

    /** Role of the user — determines what they can access in the system. */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false)
    private UserRole role;

    /** Whether this user account is active.
     *  Panel members start as inactive until they set their password. */
    @Column(name = "is_active", nullable = false)
    private boolean isActive = false;

    /** Secure token sent to panel member via email to set their password.
     *  Null for HR and Candidate users. */
    @Column(name = "activation_token")
    private String activationToken;

    /** Expiry time of the activation token — valid for 24 hours. */
    @Column(name = "token_expiry")
    private LocalDateTime tokenExpiry;

    /** Timestamp when this user account was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * Default constructor required by JPA.
     */
    public User() {
    }

    /**
     * Creates a new user with all required fields.
     * isActive is set to false and createdAt is set automatically.
     *
     * @param fullName  full name of the user
     * @param email     unique email used for login
     * @param password  encrypted password
     * @param role      role of the user — HR, PANEL or CANDIDATE
     */
    public User(String fullName, String email, String password, UserRole role) {
        this.fullName = fullName;
        this.email = email;
        this.password = password;
        this.role = role;
        this.isActive = false;
        this.createdAt = LocalDateTime.now();
    }

    /** @return the user id. */
    public Long getId() {
        return id;
    }

    /** @param id the id to set. */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return the full name of the user. */
    public String getFullName() {
        return fullName;
    }

    /** @param fullName the full name to set. */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /** @return the email address of the user. */
    public String getEmail() {
        return email;
    }

    /** @param email the email to set. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** @return the encrypted password. */
    public String getPassword() {
        return password;
    }

    /** @param password the password to set. */
    public void setPassword(String password) {
        this.password = password;
    }

    /** @return the role of this user. */
    public UserRole getRole() {
        return role;
    }

    /** @param role the role to set. */
    public void setRole(UserRole role) {
        this.role = role;
    }

    /** @return true if this user account is active. */
    public boolean isActive() {
        return isActive;
    }

    /** @param active true to activate the account, false otherwise. */
    public void setActive(boolean active) {
        isActive = active;
    }

    /** @return the activation token for password setup. */
    public String getActivationToken() {
        return activationToken;
    }

    /** @param activationToken the activation token to set. */
    public void setActivationToken(String activationToken) {
        this.activationToken = activationToken;
    }

    /** @return the expiry time of the activation token. */
    public LocalDateTime getTokenExpiry() {
        return tokenExpiry;
    }

    /** @param tokenExpiry the token expiry time to set. */
    public void setTokenExpiry(LocalDateTime tokenExpiry) {
        this.tokenExpiry = tokenExpiry;
    }

    /** @return the timestamp when this account was created. */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /** @param createdAt the creation timestamp to set. */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}